#!/bin/sh
# Generated subcommand stub
set -eu

_this="$0"
case "$_this" in
  /*) : ;;
  *) _this=$(command -v -- "$_this" 2>/dev/null || printf %s "$_this")
     case "$_this" in
       /*) : ;;
       */*) _this=$(CDPATH= cd -- "${_this%/*}" && pwd -P)/${_this##*/} ;;
       *) _this=$(CDPATH= cd -- . && pwd -P)/$_this ;;
     esac ;;
esac
_dir=${_this%/*}
_root=${_dir%/tools}
. "$_root/lib/common.sh"; . "$_root/lib/log.sh"; . "$_root/lib/args.sh"; . "$_root/lib/config.sh"; . "$_root/lib/cmd.sh"

CMD_NAME="__CMD_NAME__"
CMD_SUMMARY="Describe what __CMD_NAME__ does"
CMD_USAGE="${TOOLBOX_NAME} __CMD_USAGE_PATH__ [options]"
CMD_DESCRIPTION="Explain the behaviour of __CMD_NAME__ here."
CMD_OPTIONS=$(cat <<'__CMD_OPTIONS__'
# --flag|VALUE|Describe the flag
__CMD_OPTIONS__
)
CMD_EXAMPLES=$(cat <<'__CMD_EXAMPLES__'
${TOOLBOX_NAME} __CMD_USAGE_PATH__
__CMD_EXAMPLES__
)

while [ "$#" -gt 0 ]; do
  if cmd_maybe_handle_flag "$1"; then
    shift
    continue
  fi
  case "$1" in
    --) shift; break ;;
    -*) err "unknown option: %s" "$1"; cmd_show_help ;;
    *) break ;;
  esac
done

inf "__CMD_NAME__ is not implemented yet"
