#!/bin/sh
# Example subcommand
set -eu

_this="$0"
case "$_this" in
  /*) : ;;
  *) _this=$(command -v -- "$_this" 2>/dev/null || printf %s "$_this")
     case "$_this" in
       /*) : ;;
       */*) _this=$(CDPATH= cd -- "${_this%/*}" && pwd -P)/${_this##*/} ;;
       *) _this=$(CDPATH= cd -- . && pwd -P)/$_this ;;
     esac ;;
esac
_dir=${_this%/*}
_root=${_dir%/tools}
. "$_root/lib/common.sh"; . "$_root/lib/log.sh"; . "$_root/lib/args.sh"; . "$_root/lib/config.sh"; . "$_root/lib/cmd.sh"

CMD_NAME=${CMD_NAME:-"hello"}
CMD_SUMMARY="Print a friendly greeting"
CMD_USAGE="${TOOLBOX_NAME} ${CMD_NAME} [NAME] [--loud]"
CMD_DESCRIPTION="If NAME is omitted the current user (or 'world') is used."
CMD_OPTIONS=$(cat <<'__HELLO_OPTS__'
--loud||Shout the greeting in uppercase
__HELLO_OPTS__
)
CMD_EXAMPLES=$(cat <<__HELLO_EXAMPLES__
${PROG} hello
${PROG} hello Alice --loud
__HELLO_EXAMPLES__
)

LOUD=0

while [ "$#" -gt 0 ]; do
  if cmd_maybe_handle_flag "$1"; then
    shift
    continue
  fi
  case "$1" in
    --loud) LOUD=1; shift ;;
    --) shift; break ;;
    -*) err "unknown option: %s" "$1"; cmd_show_help ;;
    *) break ;;
  esac
done

name=${1:-${USER:-world}}

ensure_dirs
dbg "config dir: %s" "$TOOLBOX_CONFIG_DIR"

msg="Hello, $name!"
if [ "$LOUD" = 1 ]; then msg=$(printf '%s' "$msg" | tr '[:lower:]' '[:upper:]'); fi
inf "%s" "$msg"
